services:
  deb-repo:
    image: nginx:1.27-alpine
    container_name: deb-repo
    restart: unless-stopped
    volumes:
      - ./deb-repo/data:/usr/share/nginx/html:ro
      - ./deb-repo/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deb.rule=Host(`deb.kova.md`)"
      - "traefik.http.routers.deb.entrypoints=websecure"
      - "traefik.http.routers.deb.tls.certresolver=letsencrypt"
    networks:
      - proxy

  rpm-repo:
    image: nginx:1.27-alpine
    container_name: rpm-repo
    restart: unless-stopped
    volumes:
      - ./rpm-repo/data:/usr/share/nginx/html:ro
      - ./rpm-repo/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpm.rule=Host(`rpm.kova.md`)"
      - "traefik.http.routers.rpm.entrypoints=websecure"
      - "traefik.http.routers.rpm.tls.certresolver=letsencrypt"
    networks:
      - proxy

  themes:
    image: nginx:1.27-alpine
    container_name: themes
    restart: unless-stopped
    volumes:
      - ./themes/data:/usr/share/nginx/html:ro
      - ./themes/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.themes.rule=Host(`themes.kova.md`)"
      - "traefik.http.routers.themes.entrypoints=websecure"
      - "traefik.http.routers.themes.tls.certresolver=letsencrypt"
    networks:
      - proxy

networks:
  proxy:
    external: true
